name: 01 Basics - Events Filters

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes



jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: step events filters
        run: echo "This is step events filters!"
