name: 01 Basics - Events Filters
on:
  pull_request:
    types:
      - closed


jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: step number 1
        run: echo "This is step number 1!"
