name: 01 Basics - Events contexts 
run-name: Ahmed Arafa 

on:
  push:
    



jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: step events con
        run: echo ${{ toJson(github) }}
