name: 01 Basics - Events contexts 
run-name: ${{ github.actor }} Ahmed Arafa  try number ${{ github.run_number}}

on:
  push:
    



jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: step events con
        run: echo ${{ toJson(github) }}
