name: 07 Basics - needs

on:
  workflow_dispatch:
 


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: exit 1
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Run Tests
        run: echo "Running tests"

  Deploy:
    needs: [Build, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Project
        run: echo "Deploying project"
      